/**
 * Reads help/articles/manifest.json + markdown files → lib/help/articles.generated.ts
 * Run via: npm run help:build (also runs on prebuild).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const articlesRoot = path.join(root, "help/articles");
const manifestPath = path.join(articlesRoot, "manifest.json");
const outPath = path.join(root, "lib/help/articles.generated.ts");

const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

const articles = manifest.map((entry) => {
  const mdPath = path.join(articlesRoot, entry.file);
  if (!fs.existsSync(mdPath)) {
    throw new Error(`Missing markdown file: ${entry.file}`);
  }
  const content = fs.readFileSync(mdPath, "utf8");
  return {
    slug: entry.slug,
    title: entry.title,
    route: entry.route,
    role: entry.role,
    content,
  };
});

const header = `/* eslint-disable */
/**
 * Auto-generated by scripts/compile-help.mjs — do not edit by hand.
 * Source: help/articles markdown + manifest.json
 */
import type { HelpArticle } from "./types";

`;

const body = `export const HELP_ARTICLES: HelpArticle[] = ${JSON.stringify(articles, null, 2)};
`;

fs.writeFileSync(outPath, header + body, "utf8");
console.log(`[compile-help] Wrote ${articles.length} articles → lib/help/articles.generated.ts`);
